name: Aggiorna dati AIS

on:
  schedule:
    - cron: '*/20 * * * *'  # ogni 20 minuti
  workflow_dispatch:       # consente avvio manuale

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Clona il repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Installa dipendenze
        run: npm install

      - name: Esegui aggiornamento
        run: node update.js
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          AIS_API_KEY: ${{ secrets.AIS_API_KEY }}
